<div class="row">

	<div class="columns large-12 footer-inner">

		<div class="row">

			<div class="columns large-4 useful-links">
				<div>
					<h2 class="footer-title">Quick links</h2>
					<ul class="footer-list">
						<li><a href="#">Home</a></li>
						<li><a href="#">About Us</a></li>
						<li><a href="#">Products</a></li>
						<li><a href="#">Gallery</a></li>
						<li><a href="#">Contact Us</a></li>
					</ul>
				</div>
			</div>

			<div class="columns large-4 contact">
				<div>
					<h2 class="footer-title">Contactus</h2>
					<ul class="footer-list">
						<li><span class="small-icon"><img src="../images/address.png" alt=""></span>255, Willson Street,Caulfield, Melbourne</li>
						<li><span class="small-icon"><img src="../images/phone.png" alt=""></span>Tel:(122)3456789, (121)3456079, (121)2341234</li>
						<li><span class="small-icon"><img src="../images/fax.png" alt=""></span>(121)5647289, (122)34526589</li>
						<li><span class="small-icon"><img src="../images/email.png" alt=""></span>email@domain.com</li>
						<li><span class="social-media"><a href="#">t</a></span><span class="social-media"><a href="#">f</a></span><span class="social-media"><a href="#">y</a></span><span class="social-media"><a href="#">g</a></span></li>
					</ul>
				</div>
			</div>

			<div class="columns large-4 about">
				<div>
					<h2 class="footer-title">Aboutus</h2>
					<p><img src="../images/about.png" alt=""></p>
					<p>Placerat urna et tristique in! Scelerisque integer nisi pha sellus, nec phasellus arcualiquet etiam magna massa sit cursus adipiscing sed, nec? Aenean odio! Cumac dolor dapibus tincidunt lorem ipsum dolor sit esmet placerat urna et tristique in! Scelerisque integer nisi phasellus</p>
				</div>
			</div>

		</div>

	</div>

</div>
