<div class="row service">

	<div class="columns large-4">
		<h1 class="service-subtitle">Scelerisque aliquet adipiscing</h1>
		<p><img src="../images/3up1.jpg" alt="" class="threeUp"></p>
		<p> scelerisque pellentesque duis nascetur crasamet sitter sit eros egestas eu? Aliquet pid porta elit acniitem esm Risus arcu augue lorem ipsum sit dolor esmet duiscra sit eros egestas eu? Aliquet pid porta elit acnisitem sit Risus arcu augue lorem ipsum sit dolor esmet </p>
		<p> <a class="button custom">details</a> </p>
	</div>

	<div class="columns large-4">
		<h1 class="service-subtitle">Scelerisque aliquet adipiscing</h1>
		<p><img src="../images/3up2.jpg" alt="" class="threeUp"></p>
		<p> scelerisque pellentesque duis nascetur crasamet sitter sit eros egestas eu? Aliquet pid porta elit acniitem esm Risus arcu augue lorem ipsum sit dolor esmet duiscra sit eros egestas eu? Aliquet pid porta elit acnisitem sit Risus arcu augue lorem ipsum sit dolor esmet </p>
		<p> <a class="button custom">details</a> </p>
	</div>

	<div class="columns large-4">
		<h1 class="service-subtitle">Scelerisque aliquet adipiscing</h1>
		<p><img src="../images/3up1.jpg" alt="" class="threeUp"></p>
		<p> scelerisque pellentesque duis nascetur crasamet sitter sit eros egestas eu? Aliquet pid porta elit acniitem esm Risus arcu augue lorem ipsum sit dolor esmet duiscra sit eros egestas eu? Aliquet pid porta elit acnisitem sit Risus arcu augue lorem ipsum sit dolor esmet </p>
		<p> <a class="button custom">details</a> </p>
	</div>

</div>