<div class="row">
	<div class="columns large-12">
		<div class="flexcar">
			<ul class="slides">

			<li>
				<div class="row">
					<div class="columns large-3"> <img src="../images/test.jpg" alt="" class="test-img"> </div>
					<div class="columns large-9">
						<h1>Elementum phasellus, diam tempor ultrices a mauris </h1>
						<p> Elementum phasellus, diam tempor ultrices a mauris, placerat odio nunc turpis? Aenean facilisis nisi turpis parturient sed pid massa et in est, et magna turpis ac a dapibus urna </p>
						<div class="row">
							<div class="columns large-12">
								<p class="test-credit"><span class="name">Rebecca Jones,</span><span class="profession"> Seo Consultant</span>, <span class="company">XYZ Pvt Ltd</span></p>
							</div>
						</div>
					</div>
				</div>
			</li>

			<li>
				<div class="row">
					<div class="columns large-3"> <img src="../images/test1.jpg" alt="" class="test-img"> </div>
					<div class="columns large-9">
						<h1>Elementum phasellus, diam tempor ultrices a mauris </h1>
						<p> Elementum phasellus, diam tempor ultrices a mauris, placerat odio nunc turpis? Aenean facilisis nisi turpis parturient sed pid massa et in est, et magna turpis ac a dapibus urna </p>
						<div class="row">
							<div class="columns large-12">
								<p class="test-credit"><span class="name">Ricky David,</span><span class="profession"> Seo Consultant</span>, <span class="company">XYZ Pvt Ltd</span></p>
							</div>
						</div>
					</div>
				</div>
			</li>

			<li>
				<div class="row">
					<div class="columns large-3"> <img src="../images/test1.jpg" alt="" class="test-img"> </div>
					<div class="columns large-9">
						<h1>Elementum phasellus, diam tempor ultrices a mauris </h1>
						<p> Elementum phasellus, diam tempor ultrices a mauris, placerat odio nunc turpis? Aenean facilisis nisi turpis parturient sed pid massa et in est, et magna turpis ac a dapibus urna </p>
						<div class="row">
							<div class="columns large-12">
								<p class="test-credit"><span class="name">Rani Malik,</span><span class="profession"> Seo Consultant</span>, <span class="company">XYZ Pvt Ltd</span></p>
							</div>
						</div>
					</div>
				</div>
			</li>

			</ul>

			<div class="test-nav"> 
				<span class="leftarrow"><img src="../images/leftarrow.png" alt=""></span>
				<span class="rightarrow"><img src="../images/rightarrow.png" alt=""></span>
			</div>
		</div>
	</div>
</div>